apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: alb-controller
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://mcr.microsoft.com/application-lb/charts