apiVersion: v1
kind: Service
metadata:
  name: ocr-api
  namespace: ocr
  labels:
    app: ocr-api
spec:
  type: ClusterIP
  selector:
    app: ocr-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http