apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alb-controller
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: azure-alb-system
  chart:
    spec:
      chart: alb-controller
      version: "1.7.9"
      sourceRef:
        kind: HelmRepository
        name: alb-controller
        namespace: flux-system
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    albController:
      namespace: azure-alb-system
      installGatewayApiCRDs: true
      podIdentity:
        clientID: ${ALB_IDENTITY_CLIENT_ID}