apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: external-secrets-system
  chart:
    spec:
      chart: external-secrets
      version: "0.10.5"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    webhook:
      create: true
    certController:
      create: true
    # Enable Workload Identity for Azure
    serviceAccount:
      create: true
      annotations:
        azure.workload.identity/client-id: $(WORKLOAD_IDENTITY_CLIENT_ID)
        azure.workload.identity/use: "true"