apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: "2.16.0"
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  install:
    createNamespace: true
  valuesFrom:
  - kind: Secret
    name: cluster-config
    valuesKey: WORKER_IDENTITY_CLIENT_ID
    targetPath: podIdentity.azureWorkload.clientId
  - kind: Secret
    name: cluster-config
    valuesKey: TENANT_ID
    targetPath: podIdentity.azureWorkload.tenantId
  values:
    podIdentity:
      azureWorkload:
        enabled: true
    resources:
      operator:
        limits:
          memory: "256Mi"
        requests:
          memory: "128Mi"
          cpu: "100m"
      metricServer:
        limits:
          memory: "256Mi"
        requests:
          memory: "128Mi"
          cpu: "100m"