apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: "2.16.0"
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  install:
    createNamespace: true
  values:
    podIdentity:
      azureWorkload:
        enabled: true
        clientId: ${WORKLOAD_IDENTITY_CLIENT_ID}
        tenantId: ${TENANT_ID}
    resources:
      operator:
        limits:
          memory: "256Mi"
        requests:
          memory: "128Mi"
          cpu: "100m"
      metricServer:
        limits:
          memory: "256Mi"
        requests:
          memory: "128Mi"
          cpu: "100m"