apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/demo/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Variable substitution from the handoff Secret
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-config
      # Secret is in flux-system namespace (same as this Kustomization)
      optional: false