apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocr-config
  namespace: ocr
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: ocr-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Create both ConfigMap-style and connection string formats
        STORAGE_ACCOUNT_NAME: "{{ .storageaccountname | toString }}"
        SERVICE_BUS_NAMESPACE: "{{ .servicebusnamesspace | toString }}"
        SERVICE_BUS_QUEUE: "{{ .servicebusqueue | toString }}"
        KEY_VAULT_NAME: "{{ .keyvaultname | toString }}"
  data:
  - secretKey: storageaccountname
    remoteRef:
      key: storage-account-name
  - secretKey: servicebusnamesspace
    remoteRef:
      key: service-bus-namespace
  - secretKey: servicebusqueue
    remoteRef:
      key: service-bus-queue
  - secretKey: keyvaultname
    remoteRef:
      key: key-vault-name