apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocr-config
  namespace: ocr
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: ocr-config
    creationPolicy: Owner
  data:
  # Connection strings that apps need
  - secretKey: servicebus-connection-string
    remoteRef:
      key: servicebus-connection-string
  - secretKey: storage-connection-string
    remoteRef:
      key: storage-connection-string
  # Resource names for reference
  - secretKey: storage-account-name
    remoteRef:
      key: storage-account-name
  - secretKey: service-bus-namespace
    remoteRef:
      key: service-bus-namespace
  - secretKey: service-bus-queue
    remoteRef:
      key: service-bus-queue
  - secretKey: service-bus-poison-queue
    remoteRef:
      key: service-bus-poison-queue