apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: ocr
spec:
  provider:
    azurekv:
      # Placeholder to be substituted by Flux postBuild
      vaultUrl: https://$(KEY_VAULT_NAME).vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: ocr-api