apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ocr-worker-scaler
  namespace: ocr
spec:
  scaleTargetRef:
    name: ocr-worker
  minReplicaCount: 1
  maxReplicaCount: 15   # Right-sized for 500 jobs in ~5 minutes
  pollingInterval: 3   # Ultra responsive scaling (3s polling)
  cooldownPeriod: 30   # Fast recovery from scale-downs (30s vs 60s)
  # Aggressive scaling controls for high-throughput workloads
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0  # No stabilization - scale immediately
          policies:
          - type: Percent
            value: 300  # Max 300% increase per 15 seconds (extremely aggressive)
            periodSeconds: 15  # Check every 15 seconds
          - type: Pods
            value: 10   # Max 10 pods per 15 seconds (right-sized)
            periodSeconds: 15
          selectPolicy: Max  # Take maximum of both policies (aggressive)
        scaleDown:
          stabilizationWindowSeconds: 600  # Wait 10min before scale down (prevent thrashing)
          policies:
          - type: Percent
            value: 25   # Max 25% decrease per minute (more conservative)
            periodSeconds: 60
  triggers:
  # Primary trigger for normal scaling (2 messages per worker)
  - type: azure-servicebus
    metadata:
      queueName: ocr-jobs
      namespace: ${SERVICE_BUS_NAMESPACE}
      messageCount: "5"  # 5 messages per pod (right-sized concurrency)
      activationQueueLength: "1"  # Start scaling at just 1 message
    authenticationRef:
      name: ocr-worker-trigger-auth
  # Secondary trigger for burst scaling (queue depth > 100 messages)
  - type: azure-servicebus
    metadata:
      queueName: ocr-jobs
      namespace: ${SERVICE_BUS_NAMESPACE}
      messageCount: "100"  # High threshold for burst scenarios (500+ jobs)
      activationQueueLength: "100"  # Activate burst scaling at 100 messages
    authenticationRef:
      name: ocr-worker-trigger-auth