apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ocr-worker-scaler
  namespace: ocr
spec:
  scaleTargetRef:
    name: ocr-worker
  minReplicaCount: 1
  maxReplicaCount: 40  # Increased for 500+ job capacity
  pollingInterval: 10  # Very responsive scaling (10s vs 15s)
  cooldownPeriod: 30   # Fast recovery from scale-downs (30s vs 60s)
  # Aggressive scaling controls for high-throughput workloads
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0  # No stabilization - scale immediately
          policies:
          - type: Percent
            value: 200  # Max 200% increase per minute (much more aggressive)
            periodSeconds: 15  # Check every 15 seconds
          - type: Pods
            value: 20   # Max 20 pods per minute (doubled)
            periodSeconds: 15
          selectPolicy: Max  # Take maximum of both policies (aggressive)
        scaleDown:
          stabilizationWindowSeconds: 600  # Wait 10min before scale down (prevent thrashing)
          policies:
          - type: Percent
            value: 25   # Max 25% decrease per minute (more conservative)
            periodSeconds: 60
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: ocr-jobs
      namespace: ${SERVICE_BUS_NAMESPACE}
      messageCount: "5"  # Lower threshold (5 vs 10) for faster scaling
    authenticationRef:
      name: ocr-worker-trigger-auth