apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ocr-worker-scaler
  namespace: ocr
spec:
  scaleTargetRef:
    name: ocr-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: ocr-jobs
      namespace: ${SERVICE_BUS_NAMESPACE}
      messageCount: "10"
    authenticationRef:
      name: ocr-worker-trigger-auth